### ISSUE TITLE
Custom textures don't save on exterior objects.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#184] opened 2017-05-29 07:03 UTC
https://redcountyrp.com/forum/viewtopic.php?f=935&t=145778

> Adding a custom texture to an exterior furniture item doesn't work

> Attempt to place a custom texture on an exterior furniture item

**Comment by wtfrazr** [comment] 2017-05-29 10:45
Already reported
https://github.com/TommyB123/redcountyrp-bugs/issues/180

**Comment by TommyB123** [comment] 2017-05-29 13:20
Duplicate of #180. Closed.

**Closed by TommyB123** 2017-05-29 13:20 UTC
