### ISSUE TITLE
Date of last joined.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#87] opened 2017-02-03 23:31 UTC
It says I last joined on Wednesday the 1st of February 2017, server time says its 30th of January 2017.

http://i.imgur.com/165AcOL.jpg

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=140086#p1652268

**Comment by Jeroen52** [comment] 2017-02-03 23:43
Duplicate of #81.

**Closed** 2017-02-04 13:08 UTC
Labels: duplicate
