### ISSUE TITLE
Conflicting Menus on SASC's MDC

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#272] opened 2017-08-30 07:06 UTC
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=150559

When a State Court member uses the MDC, the usual menu options (from SASP) will appear. However, upon closing the menus, the RCFD dashboard menu will appear instead.

https://i.gyazo.com/1d66eb40a1b010b77d1d81834121632c.png
https://i.gyazo.com/5f10bc9259a88d6426042e97a3a206c9.png
https://i.gyazo.com/3d343c03c5351d4647da4975c6d23b71.png

**Comment by Jeroen52** [comment] 2018-02-27 11:44
I was unable to reproduce this on the latest version.

Are you sure that it is still an issue @Gigabitzz?

**Comment by CodacHomeboy** [comment] 2018-03-01 14:13
This was fixed in the 3.0 update @Jeroen52 and is no longer an issue.

**Closed** 2018-03-01 14:50 UTC
Labels: confirmed
