### ISSUE TITLE
/recharge in Monty Electronic Store.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#216] opened 2017-07-09 04:50 UTC
it's borked, probably after the map update.

https://i.gyazo.com/c137366f9165eb905e350e01755d39e1.jpg

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=148056

**Comment by TommyB123** [comment] 2017-07-11 07:56
Duplicate of #214

**Closed by TommyB123** 2017-07-11 07:56 UTC
