### ISSUE TITLE
Random checkpoints on the map.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#229] opened 2017-07-20 20:23 UTC
Recently there have been random checkpoints across the map that have been affecting players on the server. These range from refueling points to side job checkpoints and anything of the sort. It appears to happen when someone refuels their vehicle or does a side job, then it goes on other player's screen/game and it can't be removed until they either /logout or /q.

**Comment by wtfrazr** [comment] 2017-07-25 10:49
Isn't this connected with the disappearing driving school checkpoints, @TommyB123 ?

**Comment by reemyrobby** [comment] 2017-07-27 09:24
It is. The whole checkpoint system is borked. Closing this as this is a duplicate of #191.

**Closed by reemyrobby** 2017-07-27 09:24 UTC
Labels: confirmed
