### ISSUE TITLE
/changedob doesn't go over 47 years old.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#230] opened 2017-07-25 01:50 UTC
If you use /changedob for any year that's under 1970, it'll say that you're 47 years old instead of the age you desire.

**Comment by Jeroen52** [comment] 2017-07-25 01:57
Most likely a bug due to this: https://en.wikipedia.org/wiki/Unix_time

**Comment by reemyrobby** [comment] 2017-07-25 05:05
Duplicate of #15. pls fix

**Closed by reemyrobby** 2017-07-25 05:05 UTC
Labels: confirmed
