### ISSUE TITLE
Unknown command returns both regular samp message & server message

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#86] opened 2017-02-03 21:31 UTC
When doing /memes (a no excistent command), it returns "SERVER: Unknown message" aswell as the grey RCRP message informin you the cmd doesnt exist

**Comment by Jeroen52** [comment] 2017-02-03 21:49
Duplicate of #83, #84.

**Closed** 2017-02-04 00:43 UTC
Labels: duplicate
