### ISSUE TITLE
Tornado Refuel Checkpoint is bugged.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#94] opened 2017-02-12 19:44 UTC
An assistance appeared IG and I answered it. The person couldn't refuel their tornado because nothing appeared on their screen when they tried to refuel it at a gas station. The same problem happened to me when I used a fuel canister. I was unable to refuel the vehicle and the marker is just stuck there.

**Comment by wtfrazr** [comment] 2017-02-14 11:14
Not just Tornado but it happens a lot with cars. A tempeorary solution is to sit back in the car and turn the engine off, maybe drive 1-2 inches away then repeat the refuelling process.
The problem is that the script places the CP in the middle of the car and it cannot be activated, not even when you push the car away. Also there are a few scenarios when you get the CP in the position of the cap, but it doesn't work.

Can we have the old, working system back?

**Comment by DogNo** [comment] 2017-02-14 23:20
If I use /refuel in my car it's good, if I use /refuel outside of the car sometimes it's in the middle, sometimes it doesn't even appear.

**Comment by CaveFM** [comment] 2017-02-19 21:37
Happens with many other cars. Savanna is one as well.

**Comment by TommyB123** [comment] 2017-02-25 09:40
I've just released a hotfix. See if this issue still happens please.

**Comment by TommyB123** [comment] 2017-03-22 12:47
Fixed in 2.5 if it wasn't already fixed.

**Closed by TommyB123** 2017-03-22 12:47 UTC
Labels: confirmed
