### ISSUE TITLE
/outfits still fucked

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#213] opened 2017-06-30 22:30 UTC
Now only the last item will equip on new outfits or updated outfits, the rest of the objects doesn't equip..
The old outfits that were created and haven't updated since the R2, they are fine.

**Comment by Jeroen52** [comment] 2017-07-02 02:26
I might be able to add more information to this.

The maximum string length of outfit names is too short, at least in my opinion.

And it seems that if you exceed the maximum outfit name length you'll have a bugged outfit that you can't equip or delete.

**Comment by wtfrazr** [comment] 2017-07-02 18:25
Problem I had an old outfit called "Motorbike" and it had a helmet, watch and a camera in it. Since I updated so that the watch is removed, the outfit is fucked and only the camera equips since it is further down in the /clothing list than the helmet.

**Comment by CaveFM** [comment] 2017-07-04 05:36
When you get fired from a faction and have an outfit, it'll get deleted along with the clothing items you're wearing at that time.

**Comment by TommyB123** [comment] 2017-07-11 08:00
Outfit names are selected directly from the database every time the command is used. That name is never saved in server memory under your playerid or anything similar, so I doubt the outfit name is the issue since it will always be consistent even if the character limit of 32 is reached. 

I'm not sure what may be causing other issues since all I did was edit a loop to check the 7th clothing slot when saving the outfit, but I'll probably find out soon enough.

**Comment by Jeroen52** [comment] 2017-07-11 08:59
@TommyB123 Is it possible to increase the character limit of the outfit names a bit? I like to make the names of my outfits descriptive so I can easily have multiple derivatives w/o getting confused or using "casual #1" "casual #2", etcetera.

**Comment by TommyB123** [comment] 2017-07-11 09:10
Sure, I've raised the limit to 64 which should be effective immediately. 

As for the bug, I've identified the cause and it'll be fixed in the next update. Closed.

**Closed by TommyB123** 2017-07-11 09:10 UTC

**Comment by Jeroen52** [comment] 2017-07-11 09:12
Praise mister B.
